In [1]:
library(tidyverse)
library(repr)
library(tidymodels)

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──

✔ ggplot2 3.3.2     ✔ purrr   0.3.4
✔ tibble  3.0.3     ✔ dplyr   1.0.2
✔ tidyr   1.1.2     ✔ stringr 1.4.0
✔ readr   1.3.1     ✔ forcats 0.5.0

Warning message:
“package ‘ggplot2’ was built under R version 4.0.1”
Warning message:
“package ‘tibble’ was built under R version 4.0.2”
Warning message:
“package ‘tidyr’ was built under R version 4.0.2”
Warning message:
“package ‘dplyr’ was built under R version 4.0.2”
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()

Warning message:
“package ‘tidymodels’ was built under R version 4.0.2”
── Attaching packages ────────────────────────────────────── tidymodels 0.1.1 ──

✔ broom     0.7.0      ✔ recipes   0.1.13
✔ dials     0.0.9      ✔ rsample   0.0.7
✔ infer     0.5.4      ✔ tune      0.1.1
✔ modeldata 0.0.2      ✔ workflows 0.2.0
✔ parsnip   0.1.3      ✔ yardstick 0.0.7

Warning message:
“package ‘broom’ was built under R version 4.0.2”
Warning message:
“package ‘dials’ was built under R version 4.0.2”
Warning message:
“package ‘infer’ was built under R version 4.0.3”
Warning message:
“package ‘modeldata’ was built under R version 4.0.1”
Warning message:
“package ‘parsnip’ was built under R version 4.0.2”
Warning message:
“package ‘recipes’ was built under R version 4.0.1”
Warning message:
“package ‘tune’ was built under R version 4.0.2”
Warning message:
“package ‘workflows’ was built under R version 4.0.2”
Warning message:
“package ‘yardstick’ was built under R version 4.0.2”
── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ scales::discard() masks purrr::discard()
✖ dplyr::filter()   masks stats::filter()
✖ recipes::fixed()  masks stringr::fixed()
✖ dplyr::lag()      masks stats::lag()
✖ yardstick::spec() masks readr::spec()
✖ recipes::step()   masks stats::step()

To begin analyzing our data, we first loaded in all the packages we needed using the 'library' function.
Our dataset is taken from Kaggle. 

First, we had to download the dataset from the web onto the computer. Second, we uploaded the file into the juypter directory we are working in.
Next, we set the seed to ensure that the sequence of numbers that is randomly generated is reproducible and we read in the data using the 'read_csv' function with a relative pathway. Below is the data that was read.

In [2]:
set.seed(20)

alcohol_data <- read_csv("HappinessAlcoholConsumption.csv")
alcohol_data

Parsed with column specification:
cols(
  Country = col_character(),
  Region = col_character(),
  Hemisphere = col_character(),
  HappinessScore = col_double(),
  HDI = col_double(),
  GDP_PerCapita = col_double(),
  Beer_PerCapita = col_double(),
  Spirit_PerCapita = col_double(),
  Wine_PerCapita = col_double()
)

    Country              Region                          Hemisphere
1   Denmark              Western Europe                  north
2   Switzerland          Western Europe                  north
3   Iceland              Western Europe                  north
4   Norway               Western Europe                  north
5   Finland              Western Europe                  north
6   Canada               North America                   north
7   Netherlands          Western Europe                  north
8   New Zealand          Australia and New Zealand       south
9   Australia            Australia and New Zealand       south
10  Sweden               Western Europe                  north
11  Israel               Middle East and Northern Africa north
12  Austria              Western Europe                  north
13  United States        North America                   north
14  Costa Rica           Latin America and Caribbean     north
15  Germany              Western Europe                  north
16  Brazil               Latin America and Caribbean     both
17  Belgium              Western Europe                  north
18  Ireland              Western Europe                  north
19  Luxembourg           Western Europe                  north
20  Mexico               Latin America and Caribbean     north
21  Singapore            Southeastern Asia               north
22  United Kingdom       Western Europe                  north
23  Chile                Latin America and Caribbean     south
24  Panama               Latin America and Caribbean     north
25  Argentina            Latin America and Caribbean     south
26  Czech Republic       Central and Eastern Europe      north
27  United Arab Emirates Middle East and Northern Africa north
28  Uruguay              Latin America and Caribbean     south
29  Malta                Western Europe                  north
30  Colombia             Latin America and Caribbean     both
⋮   ⋮                    ⋮                               ⋮
93  South Africa         Sub-Saharan Africa              south
94  Egypt                Middle East and Northern Africa north
95  Armenia              Central and Eastern Europe      north
96  Kenya                Sub-Saharan Africa              both
97  Ukraine              Central and Eastern Europe      north
98  Ghana                Sub-Saharan Africa              north
99  Dem. Rep. Congo      Sub-Saharan Africa              south
100 Georgia              Central and Eastern Europe      north
101 Rep. Congo           Sub-Saharan Africa              south
102 Senegal              Sub-Saharan Africa              north
103 Bulgaria             Central and Eastern Europe      north
104 Zimbabwe             Sub-Saharan Africa              south
105 Malawi               Sub-Saharan Africa              south
106 Gabon                Sub-Saharan Africa              south
107 Mali                 Sub-Saharan Africa              north
108 Haiti                Latin America and Caribbean     north
109 Botswana             Sub-Saharan Africa              south
110 Comoros              Sub-Saharan Africa              south
111 Cote d'Ivoire        Sub-Saharan Africa              north
112 Cambodia             Southeastern Asia               north
113 Angola               Sub-Saharan Africa              south
114 Niger                Sub-Saharan Africa              north
115 Chad                 Sub-Saharan Africa              north
116 Burkina Faso         Sub-Saharan Africa              north
117 Madagascar           Sub-Saharan Africa              south
118 Tanzania             Sub-Saharan Africa              south
119 Liberia              Sub-Saharan Africa              north
120 Benin                Sub-Saharan Africa              north
121 Togo                 Sub-Saharan Africa              north
122 Syria                Middle East and Northern Africa north
    HappinessScore HDI GDP_PerCapita Beer_PerCapita Spirit_PerCapita
1   7.526          928  53.579       224             81
2   7.509          943  79.866       185            100
3   7.501          933  60.530       233             61
4   7.498          951  70.890       169             71
5   7.413          918  43.433       263            133
6   7.404          922  42.349       240            122
7   7.339          928  45.638       251             88
8   7.334          915  40.332       203             79
9   7.313          938  49.897       261             72
10  7.291          932  51.845       152             60
11  7.267          902  37.181        63             69
12  7.119          906  44.731       279             75
13  7.104          922  57.589       249            158
14  7.087          791  11.733       149             87
15  6.994          934  42.233       346            117
16  6.952          758   8.639       245            145
17  6.929          915  41.261       295             84
18  6.907          934  64.100       313            118
19  6.871          904 100.739       236            133
20  6.778          772   8.444       238             68
21  6.739          930  55.243        60             12
22  6.725          920  40.412       219            126
23  6.705          842  13.961       130            124
24  6.701          785  14.333       285            104
25  6.650          822  12.654       193             25
26  6.596          885  18.484       361            170
27  6.573          862  38.518        16            135
28  6.545          802  15.298       115             35
29  6.488          875  24.771       149            100
30  6.481          747   5.757       159             76
⋮   ⋮              ⋮   ⋮             ⋮              ⋮
93  4.459          696   5.280       225             76
94  4.362          694   3.548         6              4
95  4.360          749   3.606        21            179
96  4.356          585   1.463        58             22
97  4.324          746   2.186       206            237
98  4.276          588   1.517        31              3
99  4.272          452   1.712        32              3
100 4.252          776   3.866        52            100
101 4.236          612 498.000        76              1
102 4.219          499 953.000         9              1
103 4.217          810   7.469       231            252
104 4.193          532   1.029        64             18
105 4.156          474 300.000         8             11
106 4.121          698   7.079       347             98
107 4.073          421 780.000         5              1
108 4.028          496 735.000         1            326
109 3.974          712   6.954       173             35
110 3.956          502 775.000         1              3
111 3.916          486   1.535        37              1
112 3.907          576   1.270        57             65
113 3.866          577   3.309       217             57
114 3.856          351 368.000         3              2
115 3.763          405 651.000        15              1
116 3.739          420 614.000        25              7
117 3.695          517 402.000        26             15
118 3.666          533 878.000        36              6
119 3.622          432 455.000        19            152
120 3.484          512 789.000        34              4
121 3.303          500 577.000        36              2
122 3.069          536   2.058         5             35
    Wine_PerCapita
1   278
2   280
3    78
4   129
5    97
6   100
7   190
8   175
9   212
10  186
11    9
12  191
13   84
14   11
15  175
16   16
17  212
18  165
19  271
20    5
21   11
22  195
23  172
24   18
25  221
26  134
27    5
28  220
29  120
30    3
⋮   ⋮
93   81
94    1
95   11
96    2
97   45
98   10
99    1
100 149
101   9
102   7
103  94
104   4
105   1
106  59
107   1
108   1
109  35
110   1
111   7
112   1
113  45
114   1
115   1
116   7
117   4
118   1
119   2
120  13
121  19
122  16

Doing a quick analysis of the data reveals that there are 9 variables. The dataset is pretty tidy - each row is one observation - an observation of one specific country and its region, and its respective elements such as HappinessScore, HDI, GDP per capita etc. 
For our specific question, we did not need to consider all the columns in this dataset, so we selected region, Beer_PerCapita and Wine_PerCapita.
We grouped the dataset by region to tell which regions there are for when plotting it in the graph, as we want to colour by regions and label which regions there are.